In [1]:
import pandas as pd
import numpy as np

In [50]:
df=pd.read_csv('U.S._Chronic_Disease_Indicators__CDI_.csv')
df.head()

C:\Users\joshi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (7,10,18,19,20,21,23,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2015,2015,AK,Alaska,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,2,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2015,2015,AL,Alabama,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,1,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2015,2015,AR,Arkansas,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,5,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2015,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2015,2015,CA,California,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,6,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403984 entries, 0 to 403983
Data columns (total 34 columns):
YearStart                    403984 non-null int64
YearEnd                      403984 non-null int64
LocationAbbr                 403984 non-null object
LocationDesc                 403984 non-null object
DataSource                   403984 non-null object
Topic                        403984 non-null object
Question                     403984 non-null object
Response                     79323 non-null object
DataValueUnit                374119 non-null object
DataValueType                403984 non-null object
DataValue                    297817 non-null object
DataValueAlt                 273666 non-null float64
DataValueFootnoteSymbol      188019 non-null object
DatavalueFootnote            187853 non-null object
LowConfidenceLimit           246819 non-null float64
HighConfidenceLimit          246819 non-null float64
StratificationCategory1      403984 non-null object
Stratification1              403984 non-null object
StratificationCategory2      79323 non-null object
Stratification2              79323 non-null object
StratificationCategory3      79323 non-null object
Stratification3              79323 non-null object
GeoLocation                  401416 non-null object
ResponseID                   79323 non-null object
LocationID                   403984 non-null int64
TopicID                      403984 non-null object
QuestionID                   403984 non-null object
DataValueTypeID              403984 non-null object
StratificationCategoryID1    403984 non-null object
StratificationID1            403984 non-null object
StratificationCategoryID2    79324 non-null object
StratificationID2            79324 non-null object
StratificationCategoryID3    79323 non-null object
StratificationID3            79323 non-null object
dtypes: float64(3), int64(3), object(28)
memory usage: 104.8+ MB

In [3]:
df.shape

(403984, 34)

In [5]:
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'GeoLocation', 'ResponseID', 'LocationID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [11]:
df.Stratification1.unique()

array(['Overall', 'Black, non-Hispanic', 'Female', 'Hispanic', 'Male',
       'Multiracial, non-Hispanic', 'Other, non-Hispanic',
       'White, non-Hispanic', 'American Indian or Alaska Native',
       'Asian or Pacific Islander'], dtype=object)

In [12]:
df.Topic.unique()

array(['Alcohol', 'Asthma', 'Arthritis', 'Cancer', 'Diabetes',
       'Overarching Conditions', 'Tobacco', 'Chronic Kidney Disease',
       'Chronic Obstructive Pulmonary Disease', 'Cardiovascular Disease',
       'Immunization', 'Mental Health',
       'Nutrition, Physical Activity, and Weight Status',
       'Reproductive Health', 'Oral Health', 'Older Adults', 'Disability'],
      dtype=object)

In [13]:
df.DataSource.unique()

array(['YRBSS', 'BRFSS', 'NVSS', 'ACS 5-Year Estimates',
       'State Inpatient Data', 'USRDS', 'CDC School Health Profiles',
       'SEDD; SID', 'Death certificate', 'STATE',
       'Statewide central cancer registries',
       'CDC Breastfeeding Report Card', 'APIS', 'Legal Research', 'mPINC',
       'HRSA, UDS', 'ASHW', 'ANRF', 'AEDS', 'InfoUSA; USDA', 'WFRS',
       'State Emergency Department Data', 'National Immunization Survey',
       "USDA National Farmers' Market Directory",
       'Current Population Survey', 'ACS 1-Year Estimates', 'CMS CCW',
       'PRAMS', 'NSCH', 'CMS Part A Claims Data',
       'Birth Certificate, NVSS',
       "CDC Children's Food Environment State Indicator Report",
       'NVSS, Mortality'], dtype=object)

In [14]:
df.Response.unique()

array([nan, ' '], dtype=object)

In [15]:
df.Question.unique()

array(['Alcohol use among youth', 'Binge drinking prevalence among youth',
       'Binge drinking prevalence among adults aged >= 18 years',
       'Asthma mortality rate',
       'Binge drinking prevalence among women aged 18-44 years',
       'Binge drinking intensity among adults aged >= 18 years who binge drink',
       'Binge drinking frequency among adults aged >= 18 years who binge drink',
       'Heavy drinking among adults aged >= 18 years',
       'Arthritis among adults aged >= 18 years',
       'Heavy drinking among women aged 18-44 years',
       'Arthritis among adults aged >= 18 years who are obese',
       'Asthma prevalence among women aged 18-44 years',
       'Current asthma prevalence among adults aged >= 18 years',
       'Arthritis among adults aged >= 18 years who have diabetes',
       'Mammography use among women aged 50-74 years',
       'Arthritis among adults aged >= 18 years who have heart disease',
       'Activity limitation due to arthritis among adults aged >= 18 years',
       'Papanicolaou smear use among adult women aged 21-65 years',
       'Recent Papanicolaou smear use among women aged 21-44 years',
       'Diabetes prevalence among women aged 18-44 years',
       'Physical inactivity among adults aged >= 18 years with arthritis',
       'Gini Index of income inequality',
       'Fair or poor health among adults aged >= 18 years with arthritis',
       'Adults aged >= 18 years with arthritis who have taken a class to learn how to manage arthritis symptoms',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with asthma',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with asthma',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with asthma',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with asthma',
       'Current smoking among adults aged >= 18 years',
       'Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years',
       'Current cigarette smoking among youth',
       'Prevalence of chronic kidney disease among adults aged >= 18 years',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 18',
       'Cholesterol screening among adults aged >= 18 years',
       'Current cigarette smoking among women aged 18-44 years',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 45 years',
       'Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease',
       'Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease',
       'Current smokeless tobacco use among adults aged >= 18 years',
       'Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Quit attempts in the past year among current smokers',
       'Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease',
       'High cholesterol prevalence among adults aged >= 18 years',
       'Awareness of high blood pressure among adults aged >= 18 years',
       'Awareness of high blood pressure among women aged 18-44 years',
       'Taking medicine for high blood pressure control among adults aged >= 18 years with high blood pressure',
       'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes',
       'Prevalence of diagnosed diabetes among adults aged >= 18 years',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease or stroke',
       'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course',
       'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease or stroke',
       'Hospitalizations for asthma',
       'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
       'Current smokeless tobacco use among youth',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
       'Foot examination among adults aged >= 18 years with diagnosed diabetes',
       'Incidence of treated end-stage renal disease',
       'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes',
       'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes',
       'Hospitalization for stroke',
       'Influenza vaccination among noninstitutionalized adults aged >= 18 years',
       'Recent mentally unhealthy days among adults aged >= 18 years',
       'At least 14 recent mentally unhealthy days among women aged 18-44 years',
       'Obesity among adults aged >= 18 years',
       'Obesity among high school students',
       'No leisure-time physical activity among adults aged >= 18 years',
       'Soda consumption among high school students',
       'Computer use among high school students',
       'Meeting aerobic physical activity guidelines among high school students',
       'Meeting aerobic physical activity guidelines for substantial health benefits among adults aged >= 18 years',
       'Meeting aerobic physical activity guidelines for substantial health benefits and for muscle-strengthening activity among adults aged >= 18 years',
       'Meeting aerobic physical activity guidelines for additional and more extensive health benefits among adults aged >= 18 years',
       'Healthy weight among adults aged >= 18 years',
       'Current lack of health insurance among adults aged 18-64 years',
       'Healthy weight among high school students',
       'Participation in daily school physical education classes among high school students',
       'Overweight or obesity among adults aged >= 18 years',
       'Overweight or obesity among high school students',
       'Overweight or obesity among women aged 18-44 years',
       'Television viewing among high school students',
       'Median daily frequency of fruit consumption among high school students',
       'Median daily frequency of vegetable consumption among high school students',
       'Median daily frequency of vegetable consumption among adults aged >= 18 years',
       'Current health care coverage among women aged 18-44 years',
       'Fair or poor self-rated health status among adults aged >= 18 years',
       'Self-rated health status among women aged 18-44 years',
       'Recent physically unhealthy days among adults aged >= 18 years',
       'Recent activity limitation among adults aged >= 18 years',
       'Timeliness of routine health care checkup among women aged 18-44 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years who smoke',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years who smoke',
       'Incidence of treated end-stage renal disease attributed to diabetes',
       'Secondary schools that allow community-sponsored use of physical activity facilities by youth outside of normal school hours',
       'Secondary schools that allow students to purchase soda or fruit drinks',
       'Secondary schools that allow students to purchase sports drinks',
       'Secondary schools that offer less healthy foods as competitive foods',
       'Secondary schools that have a comprehensive tobacco-free school policy in place',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis',
       'Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis',
       'Hospitalization for acute myocardial infarction',
       'Amputation of a lower extremity attributable to diabetes',
       'Hospitalization with diabetes as a listed diagnosis',
       'Median daily frequency of fruit consumption among adults aged >= 18 years',
       'All teeth lost among adults aged >= 65 years',
       'Six or more teeth lost among adults aged >= 65 years',
       'No tooth loss among adults aged 18-64 years',
       'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes',
       'Visits to dentist or dental clinic among adults aged >= 18 years',
       'Proportion of older adults aged >= 65 years who are up to date on a core set of clinical preventive services',
       'Proportion of older adults aged 50-64 years who are up to date on a core set of clinical preventive services',
       'Prevalence of sufficient sleep among adults aged >= 18 years',
       'Melanoma, mortality', 'Amount of tobacco product excise tax',
       'Cancer of the prostate, mortality',
       'Cancer of the oral cavity and pharynx, mortality',
       'Invasive cancer of the oral cavity or pharynx, incidence',
       'Invasive cancer of the prostate, incidence',
       'Invasive cancer (all sites combined), incidence',
       'Invasive cancer (all sites combined), mortality',
       'Invasive cancer of the female breast, incidence',
       'Cancer of the female breast, mortality',
       'Invasive cancer of the cervix, incidence',
       'Cancer of the female cervix, mortality',
       'Cancer of the colon and recturm (colorectal), incidence',
       'Cancer of the colon and recturm (colorectal), mortality',
       'Cancer of the lung and bronchus, incidence',
       'Cancer of the lung and bronchus, mortality',
       'Invasive melanoma, incidence',
       'Live births occurring at Baby Friendly Facilities',
       'State child care regulation supports onsite breastfeeding',
       'Amount of alcohol excise tax by beverage type (beer)',
       'Amount of alcohol excise tax by beverage type (wine)',
       'Amount of alcohol excise tax by beverage type (distilled spirits)',
       'Commercial host (dram shop) liability laws',
       'Mean maternity practices in infant nutrition care (mPINC) score',
       'Oral health services at Federally Qualified Health Centers',
       'Presence of regulations pertaining to serving fruit in early care and education settings',
       'Presence of regulations pertaining to serving vegetables in early care and education settings',
       'States that allow stronger local tobacco control and prevention laws',
       'Oral Health Services at Federally Qualified Health Centers',
       'States with strong polices that require retail licenses to sell tobacco products',
       'Proportion of the population protected by a comprehensive smoke-free policy prohibiting smoking in all indoor areas of workplaces and public places, including restaurants and bars',
       'Local authority to regulate alcohol outlet density',
       'Chronic liver disease mortality',
       'Per capita alcohol consumption among persons aged >= 14 years',
       'Mortality with end-stage renal disease',
       'Mortality from diseases of the heart',
       'Mortality from coronary heart disease',
       'Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years',
       'Mortality from total cardiovascular diseases',
       'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years',
       'Mortality from heart failure',
       'Mortality from cerebrovascular disease (stroke)',
       'Mortality due to diabetes reported as any listed cause of death',
       'Mortality with diabetic ketoacidosis reported as any listed cause of death',
       'Premature mortality among adults aged 45-64 years',
       'Sale of cigarette packs',
       'Census tracts with healthier food retailers within Â½ mile of boundary',
       'Population served by community water systems that receive optimally fluoridated drinking water',
       'Percent tobacco revenue to fund at CDC recommended level',
       'Emergency department visit rate for asthma',
       'Infants breastfed at 6 months',
       'Receiving formula supplementation within the first 2 days of life among breastfed infants',
       'Farmers markets that accept Women and Infant Children (WIC) farmers market nutrition program coupons',
       'Farmers markets that accept Supplemental Nutrition Assistance Program (SNAP) benefits',
       'Number of farmers markets per 100,000 residents',
       'Poverty among women aged 18-44 years',
       'Disability among adults aged >= 65 years',
       'Prevalence of 2 or more chronic conditions among Medicare-enrolled persons aged >= 65 years',
       'High school completion among adults aged 18-24 years',
       'High school completion among women aged 18-44 years', 'Poverty',
       'Alcohol use before pregnancy', 'Pre-pregnancy hypertension',
       'Dental visits among children and adolescents aged 1-17 years',
       'Preventive dental visits among children and adolescents aged 1-17 years',
       'Cigarette smoking before pregnancy', 'Folic acid supplementation',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years',
       'Prevalence of gestational diabetes',
       'Hospitalization for heart failure among Medicare-eligible persons aged >= 65 years',
       'Hospitalization for hip fracture among Medicare-eligible persons aged >= 65 years',
       'Prevalence of pre-pregnancy diabetes',
       'Postpartum depressive symptoms',
       'Preventive dental care before pregnancy',
       'Health insurance coverage before pregnancy', 'Postpartum checkup',
       'Presence of regulations pertaining to screen time in early care and education settings',
       'Presence of regulations pertaining to avoiding sugar in early care and education settings',
       'Life expectancy at birth', 'Life expectancy at age 65 years'],
      dtype=object)

In [20]:
df.DataValueType.unique()

array(['Crude Prevalence', 'Age-adjusted Prevalence', 'Number', 'Mean',
       'Age-adjusted Mean', 'Crude Rate', 'Median',
       'Adjusted by age, sex, race and ethnicity', 'Percent',
       'Age-adjusted Rate', 'Average Annual Number', 'Yes/No',
       'Average Annual Age-adjusted Rate', 'Average Annual Crude Rate',
       'US Dollars',
       'Commercial host (dram shop) liability status for alcohol service',
       'Local control of the regulation of alcohol outlet density',
       'Per capita alcohol consumption', 'Prevalence'], dtype=object)

In [22]:
df.describe()

,YearStart,YearEnd,DataValueAlt,LowConfidenceLimit,HighConfidenceLimit,LocationID
count,403984.000000,403984.000000,2.736660e+05,246819.000000,246819.000000,403984.000000
mean,2012.729851,2012.756698,7.270473e+02,49.729946,62.654180,31.003374
std,1.546388,1.515176,1.798349e+04,83.633664,95.980311,17.700259
min,2001.000000,2001.000000,0.000000e+00,0.200000,0.420000,1.000000
25%,2011.000000,2012.000000,1.890000e+01,13.000000,20.200000,17.000000
50%,2013.000000,2013.000000,4.160000e+01,31.100000,45.600000,30.000000
75%,2014.000000,2014.000000,7.100000e+01,57.400000,72.200000,45.000000
max,2016.000000,2016.000000,3.967333e+06,1293.900000,2088.000000,78.000000

In [25]:
df.describe(include=['object'])

,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,DataValue,DataValueFootnoteSymbol,...,ResponseID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
count,403984,403984,403984,403984,403984,79323,374119,403984,297817,188019,...,79323,403984,403984,403984,403984,403984,79324,79324,79323,79323
unique,55,55,33,17,202,1,14,19,20116,19,...,1,17,201,19,3,10,1,1,1,1
top,NE,Wisconsin,BRFSS,Diabetes,Mortality from heart failure,,%,Crude Prevalence,,****,...,,DIA,CVD1_4,CrdPrev,RACE,OVR,,,,
freq,7779,7779,299921,67342,6136,79323,280119,150281,23064,80363,...,79323,67342,6136,150281,246619,63215,79324,79324,79323,79323

In [26]:
df.dtypes

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
Response                      object
DataValueUnit                 object
DataValueType                 object
DataValue                     object
DataValueAlt                 float64
DataValueFootnoteSymbol       object
DatavalueFootnote             object
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
StratificationCategory2       object
Stratification2               object
StratificationCategory3       object
Stratification3               object
GeoLocation                   object
ResponseID                    object
LocationID                     int64
TopicID                       object
QuestionID                    object
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2     object
StratificationID2             object
StratificationCategoryID3     object
StratificationID3             object
dtype: object

In [34]:
df[['Topic','YearStart','YearEnd']].head()

     Topic  YearStart  YearEnd
0  Alcohol       2015     2015
1  Alcohol       2015     2015
2  Alcohol       2015     2015
3  Alcohol       2015     2015
4  Alcohol       2015     2015

In [33]:
df[['Topic','YearStart','YearEnd']].sort_values('YearStart',ascending='True').head()

                         Topic  YearStart  YearEnd
403983  Overarching Conditions       2001     2001
403906  Overarching Conditions       2001     2001
403907  Overarching Conditions       2001     2001
403908  Overarching Conditions       2001     2001
403909  Overarching Conditions       2001     2001

In [37]:
crit1=df.YearStart==2008
crit2=df.YearEnd==2009

In [39]:
df[crit1&crit2].loc[:,'Topic'].unique()

array(['Alcohol', 'Asthma', 'Arthritis', 'Cancer', 'Diabetes',
       'Overarching Conditions', 'Tobacco', 'Chronic Kidney Disease',
       'Chronic Obstructive Pulmonary Disease', 'Cardiovascular Disease',
       'Immunization', 'Mental Health',
       'Nutrition, Physical Activity, and Weight Status',
       'Reproductive Health', 'Oral Health', 'Older Adults', 'Disability'],
      dtype=object)

In [40]:
df.Topic.values

array(['Alcohol', 'Alcohol', 'Alcohol', ..., 'Overarching Conditions',
       'Overarching Conditions', 'Overarching Conditions'], dtype=object)

In [41]:
df[df.Topic.values=='Asthma'].count()

YearStart                    31958
YearEnd                      31958
LocationAbbr                 31958
LocationDesc                 31958
DataSource                   31958
Topic                        31958
Question                     31958
Response                      8115
DataValueUnit                29541
DataValueType                31958
DataValue                    21461
DataValueAlt                 16934
DataValueFootnoteSymbol      18773
DatavalueFootnote            18758
LowConfidenceLimit           15687
HighConfidenceLimit          15687
StratificationCategory1      31958
Stratification1              31958
StratificationCategory2       8115
Stratification2               8115
StratificationCategory3       8115
Stratification3               8115
GeoLocation                  31752
ResponseID                    8115
LocationID                   31958
TopicID                      31958
QuestionID                   31958
DataValueTypeID              31958
StratificationCategoryID1    31958
StratificationID1            31958
StratificationCategoryID2     8115
StratificationID2             8115
StratificationCategoryID3     8115
StratificationID3             8115
dtype: int64

In [42]:
df[df.Topic.values=='Asthma']['Topic'].count()

31958

In [43]:
df[df.Topic.values=='Alcohol']['Topic'].count()

27697

In [44]:
df[df.Topic.values=='Diabetes']['Topic'].count()

67342

In [51]:
df

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2015,2015,AK,Alaska,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,2,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2015,2015,AL,Alabama,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,1,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2015,2015,AR,Arkansas,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,5,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2015,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2015,2015,CA,California,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,6,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
5,2015,2015,CO,Colorado,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,8,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
6,2015,2015,CT,Connecticut,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,9,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
7,2015,2015,DC,District of Columbia,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,11,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
8,2015,2015,FL,Florida,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,12,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
9,2015,2015,GA,Georgia,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,13,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
10,2015,2015,GU,Guam,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,66,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
11,2015,2015,HI,Hawaii,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,15,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
12,2015,2015,IA,Iowa,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,19,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
13,2015,2015,ID,Idaho,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,16,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
14,2015,2015,IL,Illinois,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,17,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
15,2015,2015,IN,Indiana,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,18,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
16,2015,2015,KS,Kansas,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,20,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
17,2015,2015,KY,Kentucky,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,21,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
18,2015,2015,LA,Louisiana,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,22,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
19,2015,2015,MA,Massachusetts,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,25,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
20,2015,2015,MD,Maryland,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,24,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
21,2015,2015,ME,Maine,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,23,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
22,2015,2015,MI,Michigan,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,26,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
23,2015,2015,MN,Minnesota,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,27,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
24,2015,2015,MO,Missouri,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,29,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
25,2015,2015,MS,Mississippi,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,28,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
26,2015,2015,MT,Montana,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,30,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
27,2015,2015,NC,North Carolina,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,37,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
28,2015,2015,ND,North Dakota,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,38,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
29,2015,2015,NE,Nebraska,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,31,ALC,ALC1_1,CrdPrev,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403954,2001,2001,MI,Michigan,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,26,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403955,2001,2001,MN,Minnesota,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,27,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403956,2001,2001,MO,Missouri,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,29,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403957,2001,2001,MS,Mississippi,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,28,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403958,2001,2001,MT,Montana,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,30,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403959,2001,2001,NC,North Carolina,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,37,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403960,2001,2001,ND,North Dakota,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,38,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403961,2001,2001,NE,Nebraska,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,31,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403962,2001,2001,NH,New Hampshire,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,33,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403963,2001,2001,NJ,New Jersey,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,34,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403964,2001,2001,NM,New Mexico,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,35,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403965,2001,2001,NV,Nevada,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,32,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403966,2001,2001,NY,New York,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,36,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403967,2001,2001,OH,Ohio,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,39,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403968,2001,2001,OK,Oklahoma,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,40,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403969,2001,2001,OR,Oregon,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,41,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403970,2001,2001,PA,Pennsylvania,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,42,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403971,2001,2001,RI,Rhode Island,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,44,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403972,2001,2001,SC,South Carolina,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,45,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403973,2001,2001,SD,South Dakota,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,46,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403974,2001,2001,TN,Tennessee,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,47,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403975,2001,2001,TX,Texas,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,48,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403976,2001,2001,US,United States,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,59,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403977,2001,2001,UT,Utah,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,49,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403978,2001,2001,VA,Virginia,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,51,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403979,2001,2001,VT,Vermont,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,50,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403980,2001,2001,WA,Washington,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,53,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403981,2001,2001,WI,Wisconsin,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,55,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403982,2001,2001,WV,West Virginia,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,54,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN
403983,2001,2001,WY,Wyoming,"NVSS, Mortality",Overarching Conditions,Life expectancy at age 65 years,NaN,Years,Number,...,56,OVC,OVC4_2,Nmbr,OVERALL,OVR,NaN,NaN,NaN,NaN

In [53]:
x=df.YearStart.unique()

In [54]:
x

array([2015, 2013, 2014, 2012, 2011, 2010, 2009, 2016, 2008, 2007, 2001],
      dtype=int64)